version: 2
jobs:
  build:
    docker:
      - image: circleci/node:14.4.0

    steps:
      - checkout
      - run: npm install
      - run: npm run seed
      - run: npm test
  lint:
    steps:
      - checkout
      - node/install-packages
      - run:
          name: 'linting'
          command: npm run lint