version: '2.1'
orbs:
  node: circleci/node@4.1.0
jobs:
  build:
    docker:
      - image: circleci/node:14.4.0

    steps:
      - checkout
      - run: npm install
      - run: npm run seed
      - run: npm test
  lint:
    executor: node/default
    steps:
      - checkout
      - node/install-packages
      - run:
          name: 'linting'
          command: npm run lint
workflows:
  run-unit-tests:
    jobs:
      - lint
      - test